import { useEffect, useState } from "react";
import type { Locale, SensoryProfileBaseline, WineSensoryBatchPreview, WineSensoryProfile, WineSensoryProfileSummary } from "../types";
import { api } from "../services/api";

const dimensions = ["body", "acidity", "tannin", "sweetness", "aromatic_intensity", "fruit", "wood", "spice", "minerality"];
const emptyBaseline: Omit<SensoryProfileBaseline, "id"> = { entity_type: "grape", entity_key: "", dimensions: {}, confidence: 0.5, is_active: true };

export function AdminSensoryProfilesPanel({ locale }: { locale: Locale }) {
  const italian = locale === "it";
  const words: Record<string, string> = italian ? { profiles: "Con profilo", missing: "Senza profilo", metadata: "Da metadati", validated: "Validati manualmente", low_confidence: "Bassa confidenza", body: "Corpo", acidity: "Acidità", tannin: "Tannini", sweetness: "Dolcezza", aromatic_intensity: "Intensità aromatica", fruit: "Frutto", wood: "Legno", spice: "Spezie", minerality: "Mineralità", grape: "Uva", appellation: "Denominazione", region: "Regione", wine_type: "Tipologia", hybrid: "Ibrido", manual: "Manuale" } : {};
  const label = (key: string) => words[key] || key.replace(/_/g, " ");
  const [summary, setSummary] = useState<WineSensoryProfileSummary | null>(null);
  const [profiles, setProfiles] = useState<WineSensoryProfile[]>([]);
  const [baselines, setBaselines] = useState<SensoryProfileBaseline[]>([]);
  const [editing, setEditing] = useState<WineSensoryProfile | null>(null);
  const [baselineDraft, setBaselineDraft] = useState<Omit<SensoryProfileBaseline, "id">>(emptyBaseline);
  const [editingBaseline, setEditingBaseline] = useState<SensoryProfileBaseline | null>(null);
  const [preview, setPreview] = useState<WineSensoryBatchPreview | null>(null);
  const [filter, setFilter] = useState({ source: "", validated: "", low_confidence: false, missing: false, wine_type: "", region: "", appellation: "", grape: "", producer: "" });
  const [busy, setBusy] = useState(false);
  async function load() { const query = new URLSearchParams({ limit: "30" }); for (const [key, value] of Object.entries(filter)) if (typeof value === "string" ? value.trim() : value) query.set(key, String(value).trim()); const [a, b, c] = await Promise.all([api<WineSensoryProfileSummary>("/api/v1/taste-profile/admin/summary"), api<WineSensoryProfile[]>(`/api/v1/taste-profile/admin/profiles?${query}`), api<SensoryProfileBaseline[]>("/api/v1/taste-profile/admin/baselines")]); setSummary(a); setProfiles(b); setBaselines(c); }
  useEffect(() => { void load(); }, []);
  const editDimension = <T extends { dimensions: Record<string, number | null> }>(dimension: string, value: string, target: T): T => ({ ...target, dimensions: { ...target.dimensions, [dimension]: value === "" ? null : Number(value) } });
  async function enrich() { setBusy(true); try { await api("/api/v1/taste-profile/admin/enrich-missing", { method: "POST", body: JSON.stringify({ limit: 50, allow_ai: false }) }); await load(); } finally { setBusy(false); } }
  async function saveProfile() { if (!editing) return; setBusy(true); try { await api(`/api/v1/taste-profile/admin/profiles/${editing.identity_id}`, { method: "PUT", body: JSON.stringify({ dimensions: editing.dimensions, validated: editing.validated }) }); setEditing(null); await load(); } finally { setBusy(false); } }
  async function regenerate(profile: WineSensoryProfile) { setBusy(true); try { await api(`/api/v1/taste-profile/admin/profiles/${profile.identity_id}/regenerate`, { method: "POST" }); await load(); } finally { setBusy(false); } }
  async function saveBaseline() { const baseline = editingBaseline || baselineDraft; if (!baseline.entity_key.trim()) return; setBusy(true); try { await api(editingBaseline ? `/api/v1/taste-profile/admin/baselines/${editingBaseline.id}` : "/api/v1/taste-profile/admin/baselines", { method: editingBaseline ? "PUT" : "POST", body: JSON.stringify(baseline) }); setEditingBaseline(null); setBaselineDraft(emptyBaseline); await load(); } finally { setBusy(false); } }
  async function removeBaseline(baseline: SensoryProfileBaseline) { setBusy(true); try { await api(`/api/v1/taste-profile/admin/baselines/${baseline.id}`, { method: "DELETE" }); await load(); } finally { setBusy(false); } }
  const editor = editingBaseline || baselineDraft;
  const metric: Array<[string, number]> = summary ? [["profiles", summary.wines_with_profile], ["missing", summary.wines_without_profile], ["metadata", summary.inferred_from_metadata], ["AI", summary.generated_by_ai], ["validated", summary.manually_validated], ["low_confidence", summary.low_confidence]] : [];
  return <section className="settings-card settings-card-wide admin-sensory-profiles"><div className="settings-card-heading"><div><span>{italian ? "Dati condivisi" : "Shared data"}</span><h3>{italian ? "Profili sensoriali dei vini" : "Wine Sensory Profiles"}</h3></div><button type="button" className="secondary compact" disabled={busy} onClick={() => void enrich()}>{italian ? "Genera profili mancanti" : "Generate missing profiles"}</button></div>
    <div className="detail-grid admin-sensory-summary">{metric.map(([key, value]) => <div className="detail-field" key={key}><span>{key === "AI" ? "AI" : label(key)}</span><strong>{value}</strong></div>)}</div>
    <div className="inline-form admin-sensory-filters"><label><span>{italian ? "Fonte" : "Source"}</span><select value={filter.source} onChange={(e) => setFilter({ ...filter, source: e.target.value })}><option value="">{italian ? "Tutte" : "All"}</option><option value="metadata">{italian ? "Metadati" : "Metadata"}</option><option value="hybrid">{label("hybrid")}</option><option value="ai">AI</option><option value="manual">{label("manual")}</option></select></label><label><span>{italian ? "Validazione" : "Validation"}</span><select value={filter.validated} onChange={(e) => setFilter({ ...filter, validated: e.target.value })}><option value="">{italian ? "Tutte" : "All"}</option><option value="true">{italian ? "Validati" : "Validated"}</option><option value="false">{italian ? "Non validati" : "Unvalidated"}</option></select></label><label className="admin-sensory-toggle"><input type="checkbox" checked={filter.low_confidence} onChange={(e) => setFilter({ ...filter, low_confidence: e.target.checked })} /><span>{italian ? "Bassa confidenza" : "Low confidence"}</span></label><label className="admin-sensory-toggle"><input type="checkbox" checked={filter.missing} onChange={(e) => setFilter({ ...filter, missing: e.target.checked })} /><span>{italian ? "Senza profilo" : "Missing profile"}</span></label>{([['wine_type', italian ? 'Tipologia' : 'Type'], ['region', italian ? 'Regione' : 'Region'], ['appellation', italian ? 'Denominazione' : 'Appellation'], ['grape', italian ? 'Uva' : 'Grape'], ['producer', italian ? 'Produttore' : 'Producer']] as const).map(([key, name]) => <label key={key}><span>{name}</span><input value={filter[key]} onChange={(e) => setFilter({ ...filter, [key]: e.target.value })} /></label>)}<button type="button" className="secondary compact" onClick={() => void load()}>{italian ? "Applica filtri" : "Apply filters"}</button></div>
    <div className="form-actions"><button type="button" className="secondary compact" onClick={() => void api<WineSensoryBatchPreview>("/api/v1/taste-profile/admin/batch-preview").then(setPreview)}>{italian ? "Anteprima batch" : "Batch preview"}</button></div>{preview ? <p className="admin-sensory-preview">{preview.missing} {italian ? "mancanti;" : "missing;"} {preview.deterministic} {italian ? "risolvibili senza AI;" : "resolvable without AI;"} {preview.requires_ai} AI.</p> : null}
    <div className="member-list">{profiles.map((p) => <div className="member-row" key={p.identity_id}><div><strong>{[p.producer, p.name, p.vintage].filter(Boolean).join(" · ")}</strong><span>{p.source === "metadata" && italian ? "metadati" : label(p.source)} · {Math.round(p.confidence * 100)}% · {p.validated ? (italian ? "validato" : "validated") : (italian ? "da validare" : "unvalidated")}</span></div><div className="member-actions"><button type="button" className="secondary compact" onClick={() => setEditing({ ...p, dimensions: { ...p.dimensions } })}>{italian ? "Modifica" : "Edit"}</button><button type="button" className="secondary compact" disabled={busy || p.validated} onClick={() => void regenerate(p)}>{italian ? "Reimposta inferito" : "Reset inferred"}</button></div></div>)}</div>
    {editing ? <div className="settings-help-panel"><strong>{editing.name}</strong><div className="detail-grid">{dimensions.map((d) => <label key={d}><span>{label(d)}</span><input type="number" min="0" max="1" step="0.05" value={editing.dimensions[d] ?? ""} onChange={(e) => setEditing(editDimension(d, e.target.value, editing))} /></label>)}</div><label className="admin-sensory-toggle"><input type="checkbox" checked={editing.validated} onChange={(e) => setEditing({ ...editing, validated: e.target.checked })} /><span>{italian ? "Validato" : "Validated"}</span></label><div className="form-actions"><button type="button" disabled={busy} onClick={() => void saveProfile()}>{italian ? "Salva" : "Save"}</button><button type="button" className="secondary" onClick={() => setEditing(null)}>{italian ? "Annulla" : "Cancel"}</button></div></div> : null}
    <details className="settings-help-panel"><summary>{italian ? "Baseline sensoriali" : "Sensory baselines"}</summary><div className="inline-form admin-sensory-baseline-form"><label><span>{italian ? "Tipo baseline" : "Baseline type"}</span><select value={editor.entity_type} onChange={(e) => editingBaseline ? setEditingBaseline({ ...editingBaseline, entity_type: e.target.value }) : setBaselineDraft({ ...baselineDraft, entity_type: e.target.value })}><option value="grape">{label("grape")}</option><option value="appellation">{label("appellation")}</option><option value="region">{label("region")}</option><option value="wine_type">{label("wine_type")}</option></select></label><label><span>{italian ? "Chiave" : "Key"}</span><input value={editor.entity_key} onChange={(e) => editingBaseline ? setEditingBaseline({ ...editingBaseline, entity_key: e.target.value }) : setBaselineDraft({ ...baselineDraft, entity_key: e.target.value })} /></label><label><span>{italian ? "Confidenza" : "Confidence"}</span><input type="number" min="0" max="1" step="0.05" value={editor.confidence} onChange={(e) => editingBaseline ? setEditingBaseline({ ...editingBaseline, confidence: Number(e.target.value) }) : setBaselineDraft({ ...baselineDraft, confidence: Number(e.target.value) })} /></label><button type="button" disabled={busy} onClick={() => void saveBaseline()}>{editingBaseline ? (italian ? "Salva baseline" : "Save baseline") : (italian ? "Aggiungi baseline" : "Add baseline")}</button></div><div className="detail-grid">{dimensions.map((d) => <label key={d}><span>{label(d)}</span><input type="number" min="0" max="1" step="0.05" value={editor.dimensions[d] ?? ""} onChange={(e) => editingBaseline ? setEditingBaseline(editDimension(d, e.target.value, editingBaseline)) : setBaselineDraft(editDimension(d, e.target.value, baselineDraft))} /></label>)}</div><div className="member-list">{baselines.map((b) => <div className="member-row" key={b.id}><div><strong>{label(b.entity_type)}: {b.entity_key}</strong><span>{Math.round(b.confidence * 100)}%</span></div><div className="member-actions"><button type="button" className="secondary compact" onClick={() => setEditingBaseline({ ...b, dimensions: { ...b.dimensions } })}>{italian ? "Modifica" : "Edit"}</button><button type="button" className="danger compact" disabled={busy} onClick={() => void removeBaseline(b)}>{italian ? "Elimina" : "Delete"}</button></div></div>)}</div></details>
  </section>;
}

export default AdminSensoryProfilesPanel;
