import type { Locale } from "../types";

const ACTIVITY_LABELS: Record<string, [string, string]> = {
  ai_generation: ["Generazione AI", "AI generation"],
  ai_wine_complete: ["Analisi AI completa", "Full AI analysis"],
  ai_wine_value: ["Stima valore AI", "AI value estimate"],
  ai_wine_grapes: ["Ricerca uve con AI", "AI grape research"],
  ai_wine_notes: ["Note di degustazione AI", "AI tasting notes"],
  ai_wine_drink_window: ["Finestra di beva AI", "AI drinking window"],
  ai_wine_scores: ["Ricerca punteggi AI", "AI score lookup"],
  ai_wine_comparison: ["Confronto vini con AI", "AI wine comparison"],
  ai_pairing: ["Abbinamento con AI", "AI pairing"],
  ai_buying_advice: ["Consiglio d’acquisto AI", "AI buying advice"],
  ai_label_enrichment: ["Lettura etichetta con AI", "AI label enrichment"],
  ai_wishlist_analysis: ["Analisi AI della wishlist", "AI wishlist analysis"],
  ai_regional_gap_analysis: ["Analisi AI della copertura regionale", "AI regional coverage analysis"],
  wine_created: ["Vino aggiunto", "Wine added"],
  wine_updated: ["Vino aggiornato", "Wine updated"],
  wine_deleted: ["Vino eliminato", "Wine deleted"],
  wine_consumed: ["Vino registrato come bevuto", "Wine recorded as consumed"],
  wine_photo_ai_cutout: ["Scontorno foto con AI", "AI photo cutout"],
  wine_photo_updated: ["Foto bottiglia aggiornata", "Bottle photo updated"],
  wine_photo_removed: ["Foto bottiglia rimossa", "Bottle photo removed"],
  wine_photo_reused: ["Foto bottiglia riutilizzata", "Bottle photo reused"],
  ai_cellar_command: ["Comando cantina AI", "AI cellar command"],
  ai_cellar_command_executed: ["Comando cantina AI eseguito", "AI cellar command executed"],
  ai_cellar_command_undone: ["Comando cantina AI annullato", "AI cellar command undone"],
  wine_label_recognition: ["Riconoscimento etichetta", "Label recognition"],
  wine_catalog_approved: ["Vino catalogo approvato", "Catalog wine approved"],
  wine_share_offer_created: ["Condivisione vino proposta", "Wine sharing offered"],
  wine_share_offer_accepted: ["Condivisione vino accettata", "Wine sharing accepted"],
  wine_share_offer_rejected: ["Condivisione vino rifiutata", "Wine sharing rejected"],
  wine_share_offer_revoked: ["Condivisione vino revocata", "Wine sharing revoked"],
  wine_share_offer_removed: ["Condivisione vino rimossa", "Wine sharing removed"],
  tasting_updated: ["Degustazione aggiornata", "Tasting updated"],
  tasting_deleted: ["Degustazione eliminata", "Tasting deleted"],
  wine_action: ["Azione su un vino", "Wine action"],
  wishlist_item_created: ["Vino aggiunto alla wishlist", "Wine added to wishlist"],
  wishlist_item_updated: ["Voce wishlist aggiornata", "Wishlist item updated"],
  wishlist_item_deleted: ["Voce wishlist eliminata", "Wishlist item deleted"],
  wishlist_item_converted: ["Wishlist convertita in vino", "Wishlist converted to wine"],
  wishlist_list_created: ["Lista wishlist creata", "Wishlist list created"],
  wishlist_list_updated: ["Lista wishlist aggiornata", "Wishlist list updated"],
  wishlist_list_deleted: ["Lista wishlist eliminata", "Wishlist list deleted"],
  wishlist_action: ["Azione sulla wishlist", "Wishlist action"],
  household_switched: ["Cambio cantina attiva", "Active cellar changed"],
  household_invite_sent: ["Invito cantina inviato", "Cellar invitation sent"],
  household_invite_accepted: ["Invito cantina accettato", "Cellar invitation accepted"],
  household_invite_revoked: ["Invito cantina revocato", "Cellar invitation revoked"],
  household_member_updated: ["Membro cantina aggiornato", "Cellar member updated"],
  household_member_removed: ["Membro cantina rimosso", "Cellar member removed"],
  household_action: ["Gestione cantina", "Cellar management"],
  account_preferences_updated: ["Preferenze account aggiornate", "Account preferences updated"],
  demo_cellar_visited: ["Cantina demo visitata", "Demo cellar visited"],
  passkey_configured: ["Passkey configurata", "Passkey configured"],
  passkey_removed: ["Passkey rimossa", "Passkey removed"],
  account_action: ["Impostazioni account", "Account settings"],
  data_import: ["Importazione dati", "Data import"],
  coownership_action: ["Gestione comproprietà", "Co-ownership management"],
  tag_created: ["Tag creato", "Tag created"],
  tag_updated: ["Tag aggiornato", "Tag updated"],
  tag_deleted: ["Tag eliminato", "Tag deleted"],
  tag_action: ["Gestione tag", "Tag management"],
  notification_read: ["Notifica letta", "Notification read"],
  notification_archived: ["Notifica archiviata", "Notification archived"],
  notification_restored: ["Notifica ripristinata", "Notification restored"],
  notification_deleted: ["Notifica eliminata", "Notification deleted"],
  notification_action: ["Gestione notifiche", "Notification action"],
  billing_checkout_started: ["Checkout avviato", "Checkout started"],
  billing_portal_opened: ["Portale pagamenti aperto", "Billing portal opened"],
  billing_code_redeemed: ["Codice riscattato", "Code redeemed"],
  billing_action: ["Gestione abbonamento", "Billing action"],
  support_request_sent: ["Richiesta di assistenza inviata", "Support request sent"],
  app_action: ["Azione nell’app", "App action"],
};

export function activityLabel(action: string, locale: Locale) {
  return (ACTIVITY_LABELS[action] || ACTIVITY_LABELS.app_action)[locale === "it" ? 0 : 1];
}
